# -*- coding: utf-8 -*-
"""Homwork1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVdFELbeuGy8h3u1TAaajZfNG2F1fb-k

Importem les llibreries necessaries
"""

import numpy as np

"""Volem calcular l'energia d'emissió/adsorció per nanoparticula de diferent mida en confinament fort"""

Eg = 1.42  #Band gap en eV

hbar = 1.0545718e-34  #Constant de Planck reduïda (J·s)
pi = np.pi
e = 1.602e-19  #Càrrega electrònica (C)
eps0 = 8.854e-12  #Permitivitat del buit (F/m)
eps_r = 13.1  #Permitivitat relativa

"""calcul de la massa reduïda"""

me = 9.109e-31 # massa electro
me_eff = 0.068 * me
mh_eff = 0.5 * me
mu = me_eff *mh_eff / (me_eff + mh_eff)
print('massa reduida')
print (mu)

"""rang de valors de mida"""

a = np.linspace(1e-9, 10e-9, 10) # de 100nm a 500nm comprenent 10 valors distribuits entre la mida minima i la maxima

"""calcul de l'energia en funcio de a"""

E = Eg + ((hbar**2 * pi**2) / (2 * mu * a**2))/e - ((1.8 * e**2) / (4 * pi * eps0 * eps_r * a))/e #dividim els dos termes per la carrega del electro per passar-ho tot a eV, ja que l'energia del gap està en aquestes unitats

print("Valors de E per cada a:")
for ai, Ei in zip(a, E):
    print(f"a = {ai*1e9:.1f} nm → E = {Ei:.4f} eV") # buscant com expressar cada valor d'E per la seva a corresponent he obtingut aixo

"""ara fem la representacio gràfica de E en funció de a"""

import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.plot(a * 1e9, E, label="E(a)", color="b")  # Convertim 'a' a nm
plt.xlabel("a (nm)")
plt.ylabel("E (eV)")
plt.title("Energia E en funció de la mida a")
plt.grid(False)
plt.legend()
plt.show()